### ISSUE TITLE
adb命令的一个问题

### ISSUE THREAD

**Issue by ZZKdev** [moneyDboat/wechat_jump_jump#1]
os.system('adb shell pull /sdcard/%s.png .' % str(id))

最后面的那个点代表什么意思

**Comment by moneyDboat** [comment]
后一个点代表pull图片到电脑上的目标位置

**Comment by Nanue1** [comment]
测试了下 确实分辨率 很影响结果,基本就是几十分就game over,不过挺不错的

**Comment by moneyDboat** [comment]
还有很大的改进空间
