### ISSUE TITLE
关于get_control

### ISSUE THREAD

**Issue by ghost** [moneyDboat/wechat_jump_jump#13]
我想问这行代码是如何执行的？
`x_top = int(np.mean(np.nonzero(canny_img[y_top])))`

比如下面这张图，我起初没有加入 **#消去小跳棋轮廓对边缘检测结果的干扰** 
x_top = 675 是错误的结果

加入 **#消去小跳棋轮廓对边缘检测结果的干扰** 后
x_top = 434 就正确了

![3](https://user-images.githubusercontent.com/35334781/36946955-3b87b8ac-2000-11e8-89b2-29da0657cb4a.png)

**Comment by ghost** [comment]
睡了一觉，知道原因了，小人比较高y_top扫描到的是小人不是下一个方块，所以导致x_top不正确了

**Comment by moneyDboat** [comment]
是的～
